#! /bin/bash
#HELLO HEY BRO

user_name=`logname`
function os() {
	arch=`uname -m`
	if [ "${arch}" = "x*" ]; then
		OS=DEBIAN 		
		main="/home/${user_name}/.BloodyRat/server"			
	else   	        
		OS=TERMUX		
		main="/usr/share/BloodyRat/server"
fi
}
os
cd ${main}
node index.js
