#! /bin/bash


user_name=`logname`
function os() {
	cat /etc/os-release > /dev/null 2>&1
	if [ "$?" -eq "0" ]; then
		OS=DEBIAN 		
		main="/home/${user_name}/.BloodyRat/server"			
	else
		OS=TERMUX		
		main="${T_BIN}/kali-${SYS_ARCH}/kali/home/.BloodyRat/server"
fi
}
os
cd ${main}
node index.js
